### ISSUE TITLE
Frontpage enhancements

### ISSUE THREAD

**Issue by sSwerk** [jku-vds-lab/jku-vds-lab.github.io#11]
### Transfer from Google Drive:  

- [x] Dotted link underlines in webpage intersect with text below 
- [x] Paper Title should be bold
- [x] Publication: no authors, no details -> only title + short venue, year (see Alexs’ website)
  
### Transfer from Slack:  

- [x] more vertical space between logo and content
- [x] menu font style: 
      font weight seems to be higher in design. same for other headings. increases the readability for white text on green & yellow
- [x] homepage: More publication style different than in design. on purpose?
- [x] menu buttons on homepage can be higher and white space between buttons could be removed (see design)

**Comment by sSwerk** [comment]
Regarding "Paper title should be bold" - isn't this already the case?
![image](https://user-images.githubusercontent.com/29912754/159252841-ecef7952-d160-4237-a44e-6eabac234cf4.png)

**Comment by sSwerk** [comment]
What is the wanted outcome of "Tiles instead of text only"? Is there an example somewhere available?

**Comment by sSwerk** [comment]
Regarding: "Dotted link underlines in webpage intersect with text below", should the vertical space be reduced or increased in case of a dotted link?

**Comment by sSwerk** [comment]
With commit 81b7fd6a008f04206ac0caef181315348d33c91c I increased the margin by 10px - is this enough vertical space between logo and content?

**Comment by sSwerk** [comment]
With commit https://github.com/jku-vds-lab/jku-vds-lab.github.io/commit/84c579713007f8563823b8efdc9c527e5d06bfd5 I increased the font-weight of the Menu by 200, is this ok?

was: 
![image](https://user-images.githubusercontent.com/29912754/159258991-000549de-570a-4142-82c7-cc3b934193ea.png)

now:
![image](https://user-images.githubusercontent.com/29912754/159259024-03128acd-f5f7-45a9-ab84-1d7fbbaf74ee.png)

**Comment by sSwerk** [comment]
Regarding the "more publications style", in the design Document it looks like:
![image](https://user-images.githubusercontent.com/29912754/159267894-ad805c70-a2a7-412f-980e-fd9074d7dc88.png)

Should I replace the existing tile with a button? 
![image](https://user-images.githubusercontent.com/29912754/159268039-a174b8ca-f720-48b2-a0b1-7be37b94f163.png)

**Comment by sSwerk** [comment]
@mstreit any suggestions or can I close this issue?

**Comment by mstreit** [comment]
> Regarding the "more publications style", in the design Document it looks like: ![image](https://user-images.githubusercontent.com/29912754/159267894-ad805c70-a2a7-412f-980e-fd9074d7dc88.png)
> 
> Should I replace the existing tile with a button? ![image](https://user-images.githubusercontent.com/29912754/159268039-a174b8ca-f720-48b2-a0b1-7be37b94f163.png)

yes, please.

**Comment by mstreit** [comment]
Looks good. Can you remove the dotted link underline style?

**Comment by sSwerk** [comment]
I replaced the tile with a button (home color), and removed the dotted underlink style.

**Comment by mstreit** [comment]
Thanks. The button looks good (is it similar to the one in Andreas' design?). The button hover style should be the same as for the main menu. 
Please also change the link style to a regular underline instead of the blue highlight (because that interferes with the overall design).

**Comment by sSwerk** [comment]
Both, the link style has been changed to a solid underline and the more publications button hover style is now the same as for the navigation buttons (see https://github.com/jku-vds-lab/jku-vds-lab.github.io/commit/e015032a9c769f9210896b19f90bf1807ca70fe7), is it better now?

**Comment by mstreit** [comment]
Looks good now, thanks!
